import { ApplicationConfig, provideBrowserGlobalErrorListeners, provideZoneChangeDetection } from '@angular/core';
import { provideRouter, withComponentInputBinding, withInMemoryScrolling } from '@angular/router';
import { provideHttpClient } from '@angular/common/http';
import { provideTranslateService } from '@ngx-translate/core';
import { provideTranslateHttpLoader } from '@ngx-translate/http-loader';
import {
  provideLucideIcons,
  LucideMenu,
  LucideX,
  LucideChevronDown,
  LucideArrowRight,
  LucideArrowUp,
  LucideGlobe,
  LucideCheck,
  LucideCircleCheck,
  LucideMail,
  LucidePhone,
  LucideMapPin,
  LucideSend,
  LucideMessageCircle,
  LucideLaptop,
  LucidePalette,
  LucideBriefcaseBusiness,
  LucidePrinter,
  LucideSparkles,
  LucideMessageSquareText,
  LucideSearch,
  LucideSettings2,
  LucidePackageCheck,
  LucideUserCheck,
  LucideUsers,
  LucideWorkflow,
  LucideClock,
  LucideSlidersHorizontal,
  LucideBuilding2,
  LucideUser,
  LucideRocket,
  LucideStore,
  LucideLandmark,
  LucideTrendingUp,
  LucideLifeBuoy,
  LucideShuffle,
  LucideCompass,
  LucideTarget,
  LucideShieldCheck,
  LucideSun,
  LucideMoon,
  LucideMinus,
} from '@lucide/angular';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes, withComponentInputBinding(), withInMemoryScrolling({ scrollPositionRestoration: 'top' })),
    provideHttpClient(),
    provideTranslateService({ lang: 'en', fallbackLang: 'en' }),
    provideTranslateHttpLoader({ prefix: 'i18n/', suffix: '.json' }),
    provideLucideIcons(
      LucideMenu,
      LucideX,
      LucideChevronDown,
      LucideArrowRight,
  LucideArrowUp,
      LucideGlobe,
      LucideCheck,
      LucideCircleCheck,
      LucideMail,
      LucidePhone,
      LucideMapPin,
      LucideSend,
      LucideMessageCircle,
      LucideLaptop,
      LucidePalette,
      LucideBriefcaseBusiness,
      LucidePrinter,
      LucideSparkles,
      LucideMessageSquareText,
      LucideSearch,
      LucideSettings2,
      LucidePackageCheck,
      LucideUserCheck,
      LucideUsers,
      LucideWorkflow,
      LucideClock,
      LucideSlidersHorizontal,
      LucideBuilding2,
      LucideUser,
      LucideRocket,
      LucideStore,
      LucideLandmark,
      LucideTrendingUp,
      LucideLifeBuoy,
      LucideShuffle,
      LucideCompass,
      LucideTarget,
      LucideShieldCheck,
      LucideSun,
      LucideMoon,
      LucideMinus,
    ),
  ],
};
